export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const FILTER_VIDEOGAMES_BY_GENRE = 'FILTER_VIDEOGAMES_BY_GENRE';
export const FILTER_VIDEOGAMES_BY_ORIGIN = 'FILTER_VIDEOGAMES_BY_ORIGIN';
export const GET_VIDEOGAMES_NOT_FOUND = 'GET_VIDEOGAMES_NOT_FOUND';
export const ORDER_VIDEOGAMES =  'ORDER_VIDEOGAMES';
export const GET_VIDEOGAME = 'GET_VIDEOGAME';
export const DELETE_FILTERS = 'DELETE_FILTERS';
export const CHARGE_VIDEOGAMES = 'CHARGE_VIDEOGAMES';